export const ADD_TRIP_REQUEST = "ADD_TRIP_REQUEST"
export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS "
export const ADD_TRIP_FAILED = "ADD_TRIP_FAILED"

export const GET_TRIP_REQUEST = "GET_TRIP_REQUEST"
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS"
export const GET_TRIP_FAILED = "GET_TRIP_FAILED"


export const GET_ALL_TRIP_REQUEST = "GET_ALL_TRIP_REQUEST"
export const GET_ALL_TRIP_SUCCESS = "GET_ALL_TRIP_SUCCESS"
export const GET_ALL_TRIP_FAILED = "GET_ALL_TRIP_FAILED"